/**
 * @fileoverview gRPC-Web generated client stub for kyle_chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.2
// source: chat.proto

/* eslint-disable */
// @ts-nocheck

import * as grpcWeb from 'grpc-web';

import * as google_protobuf_wrappers_pb from 'google-protobuf/google/protobuf/wrappers_pb'; // proto import: "google/protobuf/wrappers.proto"
import * as chat_pb from './chat_pb'; // proto import: "chat.proto"

export class ChatClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string };
  options_: null | { [index: string]: any };

  constructor(
    hostname: string,
    credentials?: null | { [index: string]: string },
    options?: null | { [index: string]: any },
  ) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMsgTest = new grpcWeb.MethodDescriptor(
    '/kyle_chat.Chat/SendMsgTest',
    grpcWeb.MethodType.UNARY,
    chat_pb.TestMsg,
    google_protobuf_wrappers_pb.StringValue,
    (request: chat_pb.TestMsg) => {
      return request.serializeBinary();
    },
    google_protobuf_wrappers_pb.StringValue.deserializeBinary,
  );

  sendMsgTest(
    request: chat_pb.TestMsg,
    metadata?: grpcWeb.Metadata | null,
  ): Promise<google_protobuf_wrappers_pb.StringValue>;

  sendMsgTest(
    request: chat_pb.TestMsg,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: google_protobuf_wrappers_pb.StringValue,
    ) => void,
  ): grpcWeb.ClientReadableStream<google_protobuf_wrappers_pb.StringValue>;

  sendMsgTest(
    request: chat_pb.TestMsg,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: google_protobuf_wrappers_pb.StringValue,
    ) => void,
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/kyle_chat.Chat/SendMsgTest',
        request,
        metadata || {},
        this.methodDescriptorSendMsgTest,
        callback,
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/kyle_chat.Chat/SendMsgTest',
      request,
      metadata || {},
      this.methodDescriptorSendMsgTest,
    );
  }

  methodDescriptorSendMsg = new grpcWeb.MethodDescriptor(
    '/kyle_chat.Chat/SendMsg',
    grpcWeb.MethodType.UNARY,
    chat_pb.ChatMsg,
    google_protobuf_wrappers_pb.StringValue,
    (request: chat_pb.ChatMsg) => {
      return request.serializeBinary();
    },
    google_protobuf_wrappers_pb.StringValue.deserializeBinary,
  );

  sendMsg(
    request: chat_pb.ChatMsg,
    metadata?: grpcWeb.Metadata | null,
  ): Promise<google_protobuf_wrappers_pb.StringValue>;

  sendMsg(
    request: chat_pb.ChatMsg,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: google_protobuf_wrappers_pb.StringValue,
    ) => void,
  ): grpcWeb.ClientReadableStream<google_protobuf_wrappers_pb.StringValue>;

  sendMsg(
    request: chat_pb.ChatMsg,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: google_protobuf_wrappers_pb.StringValue,
    ) => void,
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/kyle_chat.Chat/SendMsg',
        request,
        metadata || {},
        this.methodDescriptorSendMsg,
        callback,
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/kyle_chat.Chat/SendMsg',
      request,
      metadata || {},
      this.methodDescriptorSendMsg,
    );
  }

  methodDescriptorGetMsgTest = new grpcWeb.MethodDescriptor(
    '/kyle_chat.Chat/GetMsgTest',
    grpcWeb.MethodType.UNARY,
    chat_pb.GetTestMsg,
    chat_pb.TestMsg,
    (request: chat_pb.GetTestMsg) => {
      return request.serializeBinary();
    },
    chat_pb.TestMsg.deserializeBinary,
  );

  getMsgTest(
    request: chat_pb.GetTestMsg,
    metadata?: grpcWeb.Metadata | null,
  ): Promise<chat_pb.TestMsg>;

  getMsgTest(
    request: chat_pb.GetTestMsg,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: chat_pb.TestMsg) => void,
  ): grpcWeb.ClientReadableStream<chat_pb.TestMsg>;

  getMsgTest(
    request: chat_pb.GetTestMsg,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: chat_pb.TestMsg) => void,
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/kyle_chat.Chat/GetMsgTest',
        request,
        metadata || {},
        this.methodDescriptorGetMsgTest,
        callback,
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/kyle_chat.Chat/GetMsgTest',
      request,
      metadata || {},
      this.methodDescriptorGetMsgTest,
    );
  }

  methodDescriptorGetMsg = new grpcWeb.MethodDescriptor(
    '/kyle_chat.Chat/GetMsg',
    grpcWeb.MethodType.UNARY,
    chat_pb.GetChatMsg,
    chat_pb.ChatMsg,
    (request: chat_pb.GetChatMsg) => {
      return request.serializeBinary();
    },
    chat_pb.ChatMsg.deserializeBinary,
  );

  getMsg(
    request: chat_pb.GetChatMsg,
    metadata?: grpcWeb.Metadata | null,
  ): Promise<chat_pb.ChatMsg>;

  getMsg(
    request: chat_pb.GetChatMsg,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: chat_pb.ChatMsg) => void,
  ): grpcWeb.ClientReadableStream<chat_pb.ChatMsg>;

  getMsg(
    request: chat_pb.GetChatMsg,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: chat_pb.ChatMsg) => void,
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/kyle_chat.Chat/GetMsg',
        request,
        metadata || {},
        this.methodDescriptorGetMsg,
        callback,
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/kyle_chat.Chat/GetMsg',
      request,
      metadata || {},
      this.methodDescriptorGetMsg,
    );
  }
}
